version: '3.3'

services:
  db:
    image: postgres:14
    container_name: postgres
    volumes:
      - db_data_2:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env
    networks:
      - test_network

  django:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - test_network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    env_file:
      - .env
    depends_on:
      - db

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - db_data_2:/data
    command: redis-server --appendonly yes

networks:
  test_network:

volumes:
  db_data_2:
