version: '3.3'

services:
  db:
    image: postgres:14
    container_name: postgres
    restart: always
    volumes:
      - db_data_2:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env
    networks:
      - login_network

  django:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - login_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - '8080:80'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - login_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - db_data_2:/data
    command: redis-server --appendonly yes
    networks:
      - login_network

networks:
  login_network:

volumes:
  db_data_2:
