# Generated by Django 4.2.14 on 2024-08-10 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannedip',
            name='banned_until',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 10, 9, 2, 27, 118993, tzinfo=datetime.timezone.utc)),
        ),
    ]
