# Generated by Django 5.0.7 on 2024-08-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='banned_until',
            field=models.DateTimeField(null=True),
        ),
    ]
